services:
  - type: web
    name: telegram-bot-dame-polling
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main_polling.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
